language: android

android:
  components:
    - sys-img-armeabi-v7a-android-23
    - build-tools-23.0.2
    - android-23

script:
  - gradle clean build connectedCheck coveralls

cache:
  directories:
    - $HOME/.m2
