language: android

android:
  components:
    - sys-img-armeabi-v7a-android-21
    - build-tools-21.1.2
    - android-21

script:
  - gradle clean library:build library:libraryJar example:build test example:jacocoTestReport example:coveralls

cache:
  directories:
    - $HOME/.m2
